#!/bin/bash
set -e

# Configuration
SRC_DIR="src/main/java/com/mrbt/orbit"
OUTPUT="architect/architecture-graph.md"
BASE_PKG="com.mrbt.orbit"
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Validation
if [ ! -d "$SRC_DIR" ]; then
  echo "Error: $SRC_DIR not found. Run from project root."
  exit 1
fi

# Ensure output directory exists
mkdir -p "$(dirname "$OUTPUT")"

# Discover modules (directories with .java files)
MODULES=()
for dir in "$SRC_DIR"/*/; do
  module=$(basename "$dir")
  MODULES+=("$module")
done

# Counters for summary
TOTAL_ENDPOINTS=0
TOTAL_ENTITIES=0

# Start output
cat > "$OUTPUT" << EOF
<!-- AUTO-GENERATED by scripts/generate-architecture-graph.sh -->
<!-- Do not edit manually. Regenerate with: ./scripts/generate-architecture-graph.sh -->
<!-- Generated: $TIMESTAMP -->

# Orbit Architecture Graph

EOF

# --- Section 1: Module Overview & Layer Completeness ---
echo "## 1. Module Overview & Layer Completeness" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "| Module | api | core | infrastructure | exception |" >> "$OUTPUT"
echo "|--------|-----|------|----------------|-----------|" >> "$OUTPUT"

for module in "${MODULES[@]}"; do
  api="—"; core="—"; infra="—"; exc="—"
  [ -d "$SRC_DIR/$module/api" ] && api="✓"
  [ -d "$SRC_DIR/$module/core" ] && core="✓"
  [ -d "$SRC_DIR/$module/infrastructure" ] && infra="✓"
  [ -d "$SRC_DIR/$module/exception" ] && exc="✓"
  echo "| $module | $api | $core | $infra | $exc |" >> "$OUTPUT"
done
echo "" >> "$OUTPUT"
