#!/bin/bash
set -e

# Configuration
SRC_DIR="src/main/java/com/mrbt/orbit"
OUTPUT="architect/architecture-graph.md"
BASE_PKG="com.mrbt.orbit"
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Validation
if [ ! -d "$SRC_DIR" ]; then
  echo "Error: $SRC_DIR not found. Run from project root."
  exit 1
fi

# Ensure output directory exists
mkdir -p "$(dirname "$OUTPUT")"

# Discover modules (directories with .java files)
MODULES=()
for dir in "$SRC_DIR"/*/; do
  module=$(basename "$dir")
  MODULES+=("$module")
done

# Counters for summary
TOTAL_ENDPOINTS=0
TOTAL_ENTITIES=0

# Start output
cat > "$OUTPUT" << EOF
<!-- AUTO-GENERATED by scripts/generate-architecture-graph.sh -->
<!-- Do not edit manually. Regenerate with: ./scripts/generate-architecture-graph.sh -->
<!-- Generated: $TIMESTAMP -->

# Orbit Architecture Graph

EOF

# --- Section 1: Module Overview & Layer Completeness ---
echo "## 1. Module Overview & Layer Completeness" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "| Module | api | core | infrastructure | exception |" >> "$OUTPUT"
echo "|--------|-----|------|----------------|-----------|" >> "$OUTPUT"

for module in "${MODULES[@]}"; do
  api="—"; core="—"; infra="—"; exc="—"
  [ -d "$SRC_DIR/$module/api" ] && api="✓"
  [ -d "$SRC_DIR/$module/core" ] && core="✓"
  [ -d "$SRC_DIR/$module/infrastructure" ] && infra="✓"
  [ -d "$SRC_DIR/$module/exception" ] && exc="✓"
  echo "| $module | $api | $core | $infra | $exc |" >> "$OUTPUT"
done
echo "" >> "$OUTPUT"

# --- Section 2: Module Dependency Graph ---
echo "## 2. Module Dependency Graph" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo '```mermaid' >> "$OUTPUT"
echo "graph TD" >> "$OUTPUT"

# Collect unique edges using a temp file (bash 3.2 compatible)
EDGE_TMP=$(mktemp)
trap "rm -f $EDGE_TMP" EXIT

for module in "${MODULES[@]}"; do
  if [ -d "$SRC_DIR/$module" ]; then
    deps=$(grep -rh "^import ${BASE_PKG}\." "$SRC_DIR/$module" 2>/dev/null \
      | sed "s/import ${BASE_PKG}\.\([a-z_]*\)\..*/\1/" \
      | sort -u)
    for dep in $deps; do
      # Skip self-imports and cross-cutting modules
      if [ "$dep" != "$module" ] && [ "$dep" != "common" ] && [ "$dep" != "config" ]; then
        edge="${module}|${dep}"
        if ! grep -qx "$edge" "$EDGE_TMP" 2>/dev/null; then
          echo "$edge" >> "$EDGE_TMP"
          echo "  $module --> $dep" >> "$OUTPUT"
        fi
      fi
    done
  fi
done

echo '```' >> "$OUTPUT"
echo "" >> "$OUTPUT"

# --- Section 3: Cross-cutting Dependencies ---
echo "## 3. Cross-cutting Dependencies" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "| Module | common | config | security |" >> "$OUTPUT"
echo "|--------|--------|--------|----------|" >> "$OUTPUT"

CROSS_MODULES="common config security"
for module in "${MODULES[@]}"; do
  # Skip cross-cutting modules themselves
  is_cross=false
  for cross in $CROSS_MODULES; do
    [ "$module" = "$cross" ] && is_cross=true
  done
  $is_cross && continue

  row="| $module"
  for cross in $CROSS_MODULES; do
    count=$(grep -rh "^import ${BASE_PKG}\.${cross}\." "$SRC_DIR/$module" 2>/dev/null | wc -l | tr -d ' ')
    if [ "$count" -gt 0 ]; then
      row="$row | ✓ ($count)"
    else
      row="$row | —"
    fi
  done
  echo "$row |" >> "$OUTPUT"
done
echo "" >> "$OUTPUT"

# --- Section 4: Key Classes Per Module ---
echo "## 4. Key Classes Per Module" >> "$OUTPUT"
echo "" >> "$OUTPUT"

for module in "${MODULES[@]}"; do
  echo "### $module" >> "$OUTPUT"
  echo "" >> "$OUTPUT"

  # Controllers
  controllers=$(grep -rl "@RestController" "$SRC_DIR/$module" 2>/dev/null \
    | xargs -I{} basename {} .java 2>/dev/null | sort)
  if [ -n "$controllers" ]; then
    echo "**Controllers:** $(echo $controllers | sed 's/ /, /g')" >> "$OUTPUT"
  fi

  # Services
  services=$(grep -rl "@Service" "$SRC_DIR/$module" 2>/dev/null \
    | xargs -I{} basename {} .java 2>/dev/null | sort)
  if [ -n "$services" ]; then
    echo "**Services:** $(echo $services | sed 's/ /, /g')" >> "$OUTPUT"
  fi

  # Entities
  entities=$(grep -rl "@Entity" "$SRC_DIR/$module" 2>/dev/null \
    | xargs -I{} basename {} .java 2>/dev/null | sort)
  if [ -n "$entities" ]; then
    echo "**Entities:** $(echo $entities | sed 's/ /, /g')" >> "$OUTPUT"
    TOTAL_ENTITIES=$((TOTAL_ENTITIES + $(echo "$entities" | wc -w)))
  fi

  # Repositories
  repos=$(grep -rl "JpaRepository\|CrudRepository" "$SRC_DIR/$module" 2>/dev/null \
    | xargs -I{} basename {} .java 2>/dev/null | sort)
  if [ -n "$repos" ]; then
    echo "**Repositories:** $(echo $repos | sed 's/ /, /g')" >> "$OUTPUT"
  fi

  echo "" >> "$OUTPUT"
done

# --- Section 5: Database Entity Relationships ---
echo "## 5. Database Entity Relationships" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo '```mermaid' >> "$OUTPUT"
echo "erDiagram" >> "$OUTPUT"

# Build entity-to-table mapping using temp file (bash 3.2 compatible)
ENTITY_MAP_TMP=$(mktemp)
ENTITY_FILES=$(grep -rl "@Entity" "$SRC_DIR" 2>/dev/null | grep -v "Base\|SoftDeletable\|CreatedOnly")

for file in $ENTITY_FILES; do
  class_name=$(basename "$file" .java)
  table_name=$(sed -n 's/.*@Table(name *= *"\([^"]*\)".*/\1/p' "$file" 2>/dev/null)
  if [ -n "$table_name" ]; then
    echo "${class_name}=${table_name}" >> "$ENTITY_MAP_TMP"
  fi
done

# Helper: look up table name from entity class name
get_table() {
  local entity_class="$1"
  sed -n "s/^${entity_class}=//p" "$ENTITY_MAP_TMP" | head -1
}

# Parse relationships
ER_EDGE_TMP=$(mktemp)
trap "rm -f $EDGE_TMP $ENTITY_MAP_TMP $ER_EDGE_TMP" EXIT

for file in $ENTITY_FILES; do
  class_name=$(basename "$file" .java)
  source_table=$(get_table "$class_name")
  [ -z "$source_table" ] && continue

  # ManyToOne: scan for @ManyToOne then find next "private XxxEntity" line
  m2o_targets=$(awk '/@ManyToOne/{found=1} found && /private .*Entity /{match($0, /private ([A-Za-z]*Entity)/, m); if(m[1]) print m[1]; found=0}' "$file" 2>/dev/null | sort -u)
  # Fallback for BSD awk (no match with array)
  if [ -z "$m2o_targets" ]; then
    m2o_targets=$(awk '/@ManyToOne/{found=1} found && /private .*Entity /{for(i=1;i<=NF;i++){if($i ~ /Entity$/){print $i; break}}; found=0}' "$file" 2>/dev/null | sort -u)
  fi
  for target in $m2o_targets; do
    target_table=$(get_table "$target")
    [ -z "$target_table" ] && continue
    edge_key="${source_table}|${target_table}|m2o"
    if ! grep -qx "$edge_key" "$ER_EDGE_TMP" 2>/dev/null; then
      echo "$edge_key" >> "$ER_EDGE_TMP"
      echo "  ${target_table} ||--o{ ${source_table} : \"has\"" >> "$OUTPUT"
    fi
  done

  # ManyToMany: scan for @ManyToMany then find next "private List<XxxEntity>" line
  m2m_targets=$(awk '/@ManyToMany/{found=1} found && /private .*<.*Entity>/{gsub(/.*</, ""); gsub(/>.*/, ""); print; found=0}' "$file" 2>/dev/null | sort -u)
  for target in $m2m_targets; do
    target_table=$(get_table "$target")
    [ -z "$target_table" ] && continue
    edge_key="${source_table}|${target_table}|m2m"
    if ! grep -qx "$edge_key" "$ER_EDGE_TMP" 2>/dev/null; then
      echo "$edge_key" >> "$ER_EDGE_TMP"
      echo "  ${source_table} }o--o{ ${target_table} : \"many-to-many\"" >> "$OUTPUT"
    fi
  done
done

rm -f "$ENTITY_MAP_TMP" "$ER_EDGE_TMP"
echo '```' >> "$OUTPUT"
echo "" >> "$OUTPUT"
